# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: vs2017-win2016

variables:
  configuration: Release
  platform: x64

steps:
- checkout: self
  fetchDepth: 1

- task: NuGetCommand@2
  inputs:
    command: restore
    restoreSolution: '**/*.sln'

- task: VSBuild@1
  inputs:
    vsVersion: 15.0
    solution: '**/*.sln'
    msbuildArchitecture: '$(platform)'
    configuration: '$(configuration)'
    msbuildArgs: '/m'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '$(platform)/$(configuration)/**/?(*.exe|*.dll)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: files

- task: Bash@3
  condition: succeededOrFailed()
  inputs:
    targetType: inline
    script: |
      msg=$(head -1 <<< "${BUILD_SOURCEVERSIONMESSAGE}")
      curl -X POST -d '{ "value1": "$(Agent.JobStatus)", "value2": "https://dev.azure.com/kennedyri/watchdog-build/_build/results?buildId='${BUILD_BUILDURI##*/}'", "value3": "$(Build.SourceBranchName): '"${msg}"'" }' -H 'Content-Type: application/json' 'https://maker.ifttt.com/trigger/watchdog-build-notify/with/key/$(ifttt.key)'
  env:
    BUILD_BUILDURI: $(Build.BuildUri)
    BUILD_SOURCEVERSIONMESSAGE: $(Build.SourceVersionMessage)
