# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: windows-2019

variables:
  configuration: Release
  platform: x64

steps:
- checkout: self
  fetchDepth: 1

- task: NuGetCommand@2
  inputs:
    command: restore
    restoreSolution: '**/*.sln'

- task: VSBuild@1
  inputs:
    vsVersion: 16.0
    solution: '**/*.sln'
    msbuildArchitecture: '$(platform)'
    configuration: '$(configuration)'
    msbuildArgs: '/m'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '$(platform)/$(configuration)/**/?(*.exe|*.dll)'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: files
