# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: vs2017-win2016

steps:
- checkout: self
  fetchDepth: 1

- task: NuGetCommand@2
  inputs:
    command: restore
    restoreSolution: '**/*.sln'

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildArchitecture: x64
