#include "string-maps.hpp"

#define VALUE_NAME(x) { x, #x }

std::map<DWORD, std::string> const control_names
{
    VALUE_NAME(SERVICE_CONTROL_CONTINUE),
    VALUE_NAME(SERVICE_CONTROL_INTERROGATE),
    VALUE_NAME(SERVICE_CONTROL_NETBINDADD),
    VALUE_NAME(SERVICE_CONTROL_NETBINDDISABLE),
    VALUE_NAME(SERVICE_CONTROL_NETBINDENABLE),
    VALUE_NAME(SERVICE_CONTROL_NETBINDREMOVE),
    VALUE_NAME(SERVICE_CONTROL_PARAMCHANGE),
    VALUE_NAME(SERVICE_CONTROL_PAUSE),
    VALUE_NAME(SERVICE_CONTROL_PRESHUTDOWN),
    VALUE_NAME(SERVICE_CONTROL_SHUTDOWN),
    VALUE_NAME(SERVICE_CONTROL_STOP),
    VALUE_NAME(SERVICE_CONTROL_DEVICEEVENT),
    VALUE_NAME(SERVICE_CONTROL_HARDWAREPROFILECHANGE),
    VALUE_NAME(SERVICE_CONTROL_POWEREVENT),
    VALUE_NAME(SERVICE_CONTROL_SESSIONCHANGE),
    VALUE_NAME(SERVICE_CONTROL_TIMECHANGE),
    VALUE_NAME(SERVICE_CONTROL_TRIGGEREVENT),
    //VALUE_NAME(SERVICE_CONTROL_USERMODEREBOOT),
};

std::map<DWORD, std::string> const session_change_codes
{
    VALUE_NAME(WTS_CONSOLE_CONNECT),
    VALUE_NAME(WTS_CONSOLE_DISCONNECT),
    VALUE_NAME(WTS_REMOTE_CONNECT),
    VALUE_NAME(WTS_REMOTE_DISCONNECT),
    VALUE_NAME(WTS_SESSION_LOGON),
    VALUE_NAME(WTS_SESSION_LOGOFF),
    VALUE_NAME(WTS_SESSION_LOCK),
    VALUE_NAME(WTS_SESSION_LOCK),
    VALUE_NAME(WTS_SESSION_REMOTE_CONTROL),
    VALUE_NAME(WTS_SESSION_REMOTE_CONTROL),
    VALUE_NAME(WTS_SESSION_TERMINATE),
};

std::map<DWORD, std::string> const wait_results
{
    VALUE_NAME(WAIT_OBJECT_0),
    VALUE_NAME(WAIT_OBJECT_0 + 1),
    VALUE_NAME(WAIT_OBJECT_0 + 2),
    VALUE_NAME(WAIT_TIMEOUT),
    VALUE_NAME(WAIT_FAILED),
};

std::map<DWORD, std::string> const registry_types
{
    VALUE_NAME(REG_BINARY),
    VALUE_NAME(REG_DWORD),
    VALUE_NAME(REG_DWORD_LITTLE_ENDIAN),
    VALUE_NAME(REG_DWORD_BIG_ENDIAN),
    VALUE_NAME(REG_EXPAND_SZ),
    VALUE_NAME(REG_LINK),
    VALUE_NAME(REG_MULTI_SZ),
    VALUE_NAME(REG_NONE),
    VALUE_NAME(REG_QWORD),
    VALUE_NAME(REG_QWORD_LITTLE_ENDIAN),
    VALUE_NAME(REG_SZ),
};

std::map<severity_level, std::string> const severity_names
{
    { severity_level::trace, "trace" },
    { severity_level::debug, "debug" },
    { severity_level::info, "info" },
    { severity_level::warning, "warning" },
    { severity_level::error, "error" },
    { severity_level::fatal, "fatal" },
};
