name: Build

on:
- push

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Check out code
      uses: actions/checkout@master

    - name: Add MSBuild
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Set up package cache
      uses: actions/cache@v1
      id: cache
      with:
        path: packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.config') }}

    - name: Get packages
      if: steps.cache.outputs.cache-hit != 'true'
      run: nuget restore SettingsWatchdog.sln

    - name: Build
      run: msbuild -p:Configuration=Release SettingsWatchdog.sln

    - name: Publish artifacts
      uses: actions/upload-artifact@master
      with:
        name: SettingsWatchdog
        path: x64/Release/*.exe
