name: Build

on:
- push

jobs:
  build:
    runs-on: windows-2019
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static

    steps:
    - name: Check out code
      uses: actions/checkout@master

    - name: Add MSBuild
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Install & build vcpkg packages
      uses: lukka/run-vcpkg@v4
      id: vcpkg
      with:
        vcpkgGitCommitId: 3714469e0e928b06e20dde2473b90bac9c505368
        vcpkgArguments: '@${{ github.workspace }}/vcpkg-response.txt'
        appendedCacheKey: vcpkg-${{ hashFiles('${{ github.workspace }}/vcpkg-response.txt') }}

    - name: Integrate vcpkg
      run: vcpkg integrate install

    - name: Build
      run: msbuild -p:Configuration=Release SettingsWatchdog.sln

    - name: Publish artifacts
      uses: actions/upload-artifact@master
      with:
        name: SettingsWatchdog
        path: x64/Release/*.exe
