name: Build

on:
- push

jobs:
  build:
    runs-on: windows-2022
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Add MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Format source code
      run: msbuild -t:FormatCode SettingsWatchdog.sln

    - name: Check results
      shell: bash
      run: |
        while read f; do
          printf '::group::%s\n' "$f"
          printf '::warning file=%s::%s\n' "$f" "$(git diff --color=always --shortstat "$f")"
          git diff --color=always "$f"
          printf '::endgroup::\n'
        done < <(git ls-files --modified)

    - name: Install & build vcpkg packages
      uses: lukka/run-vcpkg@v10
      id: vcpkg
      with:
        runVcpkgInstall: true

    - name: Integrate vcpkg
      run: vcpkg integrate install

    - name: Build
      run: msbuild -p:Configuration=Release SettingsWatchdog.sln

    - name: Publish artifacts
      uses: actions/upload-artifact@master
      with:
        name: SettingsWatchdog
        path: x64/Release/*.exe
